"""
Expert trace format for PRISM training data.

Each training example consists of a 3-phase expert trace:
  Phase 1 (Solve):   Domain expert solves the problem
  Phase 2 (Verify):  Expert reviews and diagnoses errors
  Phase 3 (Correct): Expert produces corrected final solution

A TraceExample is the parsed representation of one generated trace.
"""

import json
import re
import logging
from dataclasses import dataclass, asdict
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class TraceExample:
    """
    One complete expert trace example for PRISM training.

    Fields:
        problem_id: Unique identifier for the problem.
        problem: Problem statement (text, possibly with image reference).
        domain: Primary PRISM domain (algebra/geometry/combinatorics/number_theory/misc).
        ground_truth: Ground-truth answer.
        solve_trace: Phase 1 — domain expert's solution attempt.
        verify_trace: Phase 2 — verification/diagnosis of the solution.
        correct_trace: Phase 3 — corrected final solution.
        teacher_model: Teacher model used for generation.
        solve_correct: Whether Phase 1 answer matches ground truth.
        correct_correct: Whether Phase 3 answer matches ground truth.
        total_tokens: Total token count across all 3 phases.
        image_path: Path to image file if problem has diagram (optional).
    """
    problem_id: str
    problem: str
    domain: str
    ground_truth: str
    solve_trace: str
    verify_trace: str
    correct_trace: str
    teacher_model: str = ""
    solve_correct: bool = False
    correct_correct: bool = False
    total_tokens: int = 0
    image_path: Optional[str] = None
    free_solve: bool = False   # True = Phase 1 had no reference → may be wrong (negative example)

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "TraceExample":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    def to_jsonl(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

    @classmethod
    def from_jsonl(cls, line: str) -> "TraceExample":
        return cls.from_dict(json.loads(line))

    def is_valid(self, max_tokens: int = 65536) -> bool:
        """
        Check quality filter: all 3 phases non-empty, total tokens ≤ max.

        Note: correct_correct is tracked as a quality stat but NOT used to
        filter here — the reformulation approach (giving teacher the correct
        answer) means the trace is valid even if answers_match() fails due
        to LaTeX normalization edge cases.
        """
        if not self.solve_trace or not self.verify_trace or not self.correct_trace:
            return False
        return self.total_tokens <= max_tokens


def parse_trace(raw_output: str) -> dict:
    """
    Parse raw teacher output that contains phase-tagged content.

    Expected format (generated by phase_prompts.py):
        <phase1_solve>
        ... solution attempt ...
        </phase1_solve>
        <phase2_verify>
        ... verification ...
        </phase2_verify>
        <phase3_correct>
        ... corrected solution ...
        </phase3_correct>

    Returns dict with keys: solve, verify, correct (or empty strings).
    """
    def extract_tag(text: str, tag: str) -> str:
        pattern = rf"<{tag}>(.*?)</{tag}>"
        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return ""

    return {
        "solve": extract_tag(raw_output, "phase1_solve"),
        "verify": extract_tag(raw_output, "phase2_verify"),
        "correct": extract_tag(raw_output, "phase3_correct"),
    }


def format_trace_prompt(
    problem: str,
    phase: int,
    domain: str,
    solve_trace: str = "",
    verify_trace: str = "",
) -> str:
    """
    Format the input prompt for a specific phase of trace generation.

    Args:
        problem: Problem statement.
        phase: 0=Solve, 1=Verify, 2=Correct.
        domain: PRISM domain name.
        solve_trace: Phase 1 output (needed for phases 2 and 3).
        verify_trace: Phase 2 output (needed for phase 3).

    Returns:
        Formatted prompt string for the teacher model.
    """
    from prism.generation.phase_prompts import get_phase_system_prompt, get_phase_user_prompt
    system = get_phase_system_prompt(domain, phase)
    user = get_phase_user_prompt(problem, phase, domain, solve_trace, verify_trace)
    return {"system": system, "user": user}


def extract_final_answer(trace: str) -> str:
    """
    Extract the final numerical or symbolic answer from a trace.
    Looks for common answer patterns.
    """
    # Pattern: \boxed{...}
    boxed = re.search(r"\\boxed\{([^}]+)\}", trace)
    if boxed:
        return boxed.group(1).strip()

    # Pattern: "The answer is X" or "= X" at end
    answer_pattern = re.search(
        r"(?:the\s+answer\s+is|=\s*|answer:\s*)([^\n.]+)",
        trace,
        re.IGNORECASE,
    )
    if answer_pattern:
        return answer_pattern.group(1).strip()

    # Last number in text
    numbers = re.findall(r"-?\d+(?:\.\d+)?(?:/\d+)?", trace)
    if numbers:
        return numbers[-1]

    return ""


def answers_match(predicted: str, ground_truth: str) -> bool:
    """
    Check if two answer strings match after normalization.
    Handles common formatting differences.
    """
    def normalize(s: str) -> str:
        s = s.strip().lower()
        # Remove LaTeX formatting
        s = re.sub(r"\\[a-zA-Z]+\{([^}]*)\}", r"\1", s)
        s = re.sub(r"\\[a-zA-Z]+", "", s)
        # Remove whitespace
        s = re.sub(r"\s+", "", s)
        # Remove trailing zeros in decimals
        s = re.sub(r"\.0+$", "", s)
        return s

    pred_norm = normalize(predicted)
    gt_norm = normalize(ground_truth)

    if pred_norm == gt_norm:
        return True

    # Try numeric comparison
    try:
        from fractions import Fraction
        pred_frac = Fraction(pred_norm)
        gt_frac = Fraction(gt_norm)
        return pred_frac == gt_frac
    except (ValueError, ZeroDivisionError):
        pass

    return False
